### ISSUE TITLE
Komodo Notary Season 4

### ISSUE THREAD

**Issue by tonymorony** [jl777/chips3#40]
Dear Chips team,

We are pleased to release the new Komodo 0.6.0 version, called "Draconic Serpent," which will hardfork the Komodo network to the 4th dPoW season on June 14th, 2020.
Exact height/timestamp can be found here ( approx. June 14th, 2020 03:00:00 PM UTC) : https://github.com/KomodoPlatform/komodo/blob/master/src/komodo_globals.h#L48

List of the third-party pubkeys for this season can be found here: https://github.com/KomodoPlatform/dPoW/blob/s4/iguana/3rd_party#L15

Please update your codebase accordingly for dPoW consensus protection and update infrastructure daemons/exchanges. We recommend contacting exchanges you listed on to pause all wallet-operations (withdraws & deposits) from June 13th, 12:00 PM UTC until June 15th 12:00 PM UTC in order to ensure a smooth network transition.

Have a great day and stay safe!

**Comment by phm87** [comment]
Dear @tonymorony ,

Thank you for the info/warning and thank you for the detailed infos.
I think that @CHMEX and @NutellaLicka took care of doing it.

https://github.com/jl777/chips3/pull/41
https://github.com/chips-blockchain/chips/pull/1

Thank you
